config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  resources :users
  resources :orders
  resources :line_items
  resources :carts
  root 'store#index', as: 'store_index'
  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/order.rb
require 'pago'

class Order < ApplicationRecord
  has_many :line_items, dependent: :destroy
  enum pay_type: {
    "Check" => 0,
    "Credit card" => 1,
    "Purchase order" => 2
  }

  validates :name, :address, :email, presence: true
  validates :pay_type, inclusion: pay_types.keys

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end

  def charge!(pay_type_params)
    payment_details = {}
    payment_method = nil

    case pay_type
    when "Check"
      payment_method = :check
      payment_details[:routing] = pay_type_params[:routing_number]
      payment_details[:account] = pay_type_params[:account_number]
    when "Credit card"
      payment_method = :credit_card
      month, year = pay_type_params[:expiration_date].split(//)
      payment_details[:cc_num] = pay_type_params[:credit_card_number]
      payment_details[:expiration_month] = month
      payment_details[:expiration_year] = year
    when "Purchase order"
      payment_method = :po
      payment_details[:po_num] = pay_type_params[:po_number]
    else
      raise "Unknown pay_type #{pay_type}"
    end

    payment_result = Pago.make_payment(
      order_id: id,
      payment_method: payment_method,
      payment_details: payment_details
    )

    if payment_result.succeeded?
      OrderMailer.received(self).deliver_later
    else
      raise payment_result.error
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_before_action :authorize, only: %i[ new create ]
  include CurrentCart
  before_action :set_cart, only: %i[ new create]
  before_action :ensure_cart_is_not_empty, only: %i[ new ]
  before_action :set_order, only: %i[ show edit update destroy ]

  # GET /orders or /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1 or /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)
    @order.add_line_items_from_cart(@cart)

    respond_to do |format|
      if @order.save
        Cart.destroy(session[:cart_id])
        session[:cart_id] = nil
        ChargeOrderJob.perform_later(@order, order_params)
        format.html { redirect_to store_index_url, notice: "Thank you for your order." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to order_url(@order), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def ensure_cart_is_not_empty
    if @cart.line_items.empty?
      redirect_to store_index_url, notice: 'Your cart is empty'
    end
  end

  def pay_type_params
    if order_params[:pay_type] == "Credit card"
      param.require(:order).permit(:credit_cart_number, :expiration_date)
    elsif order_params[:pay_type] == "Check"
      param.require(:order).permit(:routing_number, :account_number)
    elsif order_params[:pay_type] == "Purchase order"
      param.require(:order).permit(:po_number)
    else
      {}
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def order_params
    params.require(:order).permit(:name, :address, :email, :pay_type)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_cc.html.erb
<fieldset data-payment-target="additionalFields" data-type="Credit card">
  <div class="my-5">
    <%= form.label :credit_card_number %>
    <%= form.password_field :credit_card_number, class: "input-field" %>
  </div>
  <div class="my-5">
    <%= form.label :expiration_date %>
    <%= form.text_field :expiration_date, class: "input-field", size: 9, placeholder: "e.g. 03/22" %>
  </div>
</fieldset>

app/views/orders/_check.html.erb
<fieldset data-payment-target="additionalFields" data-type="Check">
  <div class="my-5">
    <%= form.label :routing_number %>
    <%= form.text_field :routing_number, class: "input-field" %>
  </div>
  <div class="my-5">
    <%= form.label :account_number %>
    <%= form.password_field :account_number, class: "input-field" %>
  </div>
</fieldset>

app/views/orders/_form.html.erb
<%= form_with(model: order, class: "contents") do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "input-field" %>
  </div>

  <div class="my-5">
    <%= form.label :address %>
    <%= form.text_area :address, rows: 4, class: "input-field" %>
  </div>

  <div class="my-5">
    <%= form.label :email %>
    <%= form.text_field :email, class: "input-field" %>
  </div>

  <div data-controller="payment">
    <div class="my-5">
      <%= form.label :pay_type %>
      <%= form.select :pay_type, Order.pay_types.keys,
                     { prompt: 'Select a payment method' },
                     'data-payment-target' => 'selection',
                     'data-action' => 'payment#showAdditionalFields',
                     class: "input-field" %>
    </div>

    <%= render partial: 'check', locals: { form: form } %>
    <%= render partial: 'cc', locals: { form: form } %>
    <%= render partial: 'po', locals: { form: form } %>
  </div>

  <div class="inline">
    <%= form.submit 'Place Order', class: "rounded-lg py-3 px-5 bg-green-200 text-black inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/orders/_order.html.erb
<div id="<%= dom_id order %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= order.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Address:</strong>
    <%= order.address %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Email:</strong>
    <%= order.email %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Pay type:</strong>
    <%= order.pay_type %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this order", order, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this order', edit_order_path(order), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/orders/_po.html.erb
<fieldset data-payment-target="additionalFields" data-type="Purchase order">
  <div class="my-5">
    <%= form.label :po_number %>
    <%= form.number_field :po_number, class: "input-field" %>
  </div>
</fieldset>

app/views/orders/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing order</h1>

  <%= render "form", order: @order %>

  <%= link_to "Show this order", @order, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to orders", orders_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/orders/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Orders</h1>
    <%= link_to 'New order', new_order_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="orders" class="min-w-full">
    <%= render @orders %>
  </div>
</div>

app/views/orders/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Please Enter Your Details</h1>

  <%= render "form", order: @order %>
</div>

app/views/orders/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @order %>

    <%= link_to 'Edit this order', edit_order_path(@order), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this order', order_path(@order), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to orders', orders_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>